version: '3.8'

services:
  app:
    build: .
    environment:
      - USER_NAME=Vishesh
      - TASK=Learn Docker with Postgres
      - DB_HOST=db
      - DB_NAME=tasksdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=tasksdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
